# Generated by Django 3.0.2 on 2020-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField()),
                ('LastName', models.TextField()),
                ('AddressLine1', models.TextField()),
                ('AddressLine2', models.TextField()),
                ('City', models.TextField()),
                ('State', models.TextField()),
                ('ZipCode', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Attending', models.BooleanField()),
            ],
        ),
    ]
