# Generated by Django 3.0.2 on 2020-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='AddressLine2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='Attending',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
