# Generated by Django 3.0.2 on 2020-01-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20200125_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='AddressLine2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='Attending',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='Email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
