# Generated by Django 3.0.2 on 2020-01-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_auto_20200129_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='AddressLine2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='Attending',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
