# Generated by Django 3.0.2 on 2020-01-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_auto_20200129_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='InvitationID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
