# Generated by Django 3.0.2 on 2020-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_guest_guestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='Status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='UpdateBy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
