# Generated by Django 3.0.2 on 2020-01-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_auto_20200130_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='Status',
            new_name='RSVPID',
        ),
    ]
