# Generated by Django 3.0.2 on 2020-02-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_weddingparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingparty',
            name='About',
            field=models.TextField(null=True),
        ),
    ]
