# Generated by Django 3.0.2 on 2020-02-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0011_weddingparty_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvitationID', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='City',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='RSVPID',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='State',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='ZipCode',
        ),
        migrations.AlterField(
            model_name='guest',
            name='GuestID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='InvitationID',
            field=models.TextField(default='tbd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weddingparty',
            name='About',
            field=models.TextField(default='tbd'),
            preserve_default=False,
        ),
    ]
