# Generated by Django 3.0.2 on 2020-02-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0012_auto_20200203_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='PlusOne',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='PlusOneFirstName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='PlusOneLastName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
