# Generated by Django 3.0.2 on 2020-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0013_auto_20200203_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='PlusOneAttending',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
