# Generated by Django 3.0.2 on 2020-02-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0014_guest_plusoneattending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingparty',
            name='Relation',
            field=models.TextField(choices=[('Bride', 'Bride'), ('Groom', 'Groom')]),
        ),
    ]
