# Generated by Django 3.0.2 on 2020-02-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20200209_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='InvitationID',
            field=models.TextField(),
        ),
    ]
